### Analyse beginnt
### CSV Importieren -> pokemon_bereinigt und moves_bereinigt ⬇️

In [3]:
import pandas as pd

df_pokemon = pd.read_csv("../data/pokemon_bereinigt.csv", index_col="id")
df_moves = pd.read_csv("../data/moves_bereinigt.csv", index_col="move_id")

### Import Check ⬇️

In [5]:
df_pokemon

,name,hp,angriff,verteidigung,speed,sp_angriff,sp_verteidigung,typ1,typ2
id,,,,,,,,,
1,BISASAM,45,49,49,45,65,65,Gras,Gift
2,BISAKNOSP,60,62,63,60,80,80,Gras,Gift
3,BISAFLOR,80,82,83,80,100,100,Gras,Gift
4,GLUMANDA,39,52,43,65,60,50,Feuer,NaN
5,GLUTEXO,58,64,58,80,80,65,Feuer,NaN
...,...,...,...,...,...,...,...,...,...
147,DRATINI,41,64,45,50,50,50,Drache,NaN
148,DRAGONIR,61,84,65,70,70,70,Drache,NaN
149,DRAGORAN,91,134,95,80,100,100,Drache,Flug
150,MEWTU,106,110,90,130,154,90,Psycho,NaN
151,MEW,100,100,100,100,100,100,Psycho,NaN

In [6]:
df_moves

            move_name  effekt  staerke     typ  genauigkeit  pp
move_id
1               PFUND       0       40  Normal          100  35
2        KARATESCHLAG      43       50   Kampf          100  25
3          DUPLEXHIEB      29       15  Normal           85  10
4         KOMETENHIEB      29       18  Normal           85  15
5            MEGAHIEB       0       80  Normal           85  20
...               ...     ...      ...     ...          ...  ..
161         TRIPLETTE      36       80  Normal          100  10
162         SUPERZAHN      40        1  Normal           90  10
163         SCHLITZER      43       70  Normal          100  20
164         DELEGATOR      79        0  Normal            0  10
165       VERZWEIFLER      48       50  Normal          100   1

[165 rows x 6 columns]

### Typverteilung
### Als erstes Typ 1 Verteilung Check ⬇️

In [7]:
typ1_verteilung = df_pokemon["typ1"].value_counts()
typ1_verteilung

typ1
Wasser     28
Normal     24
Gift       14
Gras       12
Feuer      12
Käfer      12
Elektro     9
Gestein     9
Psycho      8
Boden       8
Kampf       7
Geist       3
Drache      3
Eis         2
Name: count, dtype: int64

### Wasser dominiert ganz klar mit 28 Pokemon (so dominant weil Kanto viele Wasserrouten hat?)
### Normal ist zweithäufigst mit 24 Pokemon
### Gras, Feuer, Käfer sind gleichauf mit je 12
### Insgesamt sind 14 verschiedene Typen vorhanden
### Jetzt noch Typ 2 Checken ⬇️

In [8]:
typ2_verteilung = df_pokemon["typ2"].value_counts()
typ2_verteilung

typ2
Gift       19
Flug       19
Boden       6
Psycho      6
Wasser      4
Eis         3
Stahl       2
Gras        2
Gestein     2
Kampf       1
Name: count, dtype: int64

### Gift und Flug dominieren als Zweittyp mit je 19, macht Sinn weil viele Pokemon in Kanto Käfer/Gift oder Normal/Flug sind
### Nur 10 verschiedene Zweittypen, viele typen kommen gar nicht als Zweittyp vor wie zB Feuer, Elektro, Normal)
### Wie in df_pokemon sichtbar haben 87 Pokemon keinen Zweittyp
### Als nächstes beide zusammenführen, wie viele Pokemon gibt es pro Typ insgesamt? ⬇️

In [9]:
import pandas as pd

alle_typen = pd.concat([df_pokemon["typ1"], df_pokemon["typ2"].dropna()])
gesamt_verteilung = alle_typen.value_counts()
gesamt_verteilung

Gift       33
Wasser     32
Normal     24
Flug       19
Boden      14
Gras       14
Psycho     14
Feuer      12
Käfer      12
Gestein    11
Elektro     9
Kampf       8
Eis         5
Geist       3
Drache      3
Stahl       2
Name: count, dtype: int64

### Gift springt von Platz 3 auf Platz 1 (als Zweittyp sehr beliebt)
### Wassser bleibt stark auf Platz 2
### Normal fällt nun auf Platz 3
### Laut Pokewiki hat Gen1 genau 15 Typen https://pokewiki.de/Typen
### In Gen2 kamen Unlicht und Stahl hinzu
### Unlicht fehlt jedoch da Kanto Pokemon in Gen1 Designed wurden, also bevor Unlicht existierte, somit gibt es keine Unlicht Pokemon in Kanto
### Bei Stahl sollte es eigentlich auch so sein, wird jedoch ein Sonderfall sein weil Magnetilo/Magneton nachträglich von Elektro zu Elektro/Stahl geändert wurde
### Deshalb taucht Stahl trotzdem in Daten auf. Quelle -> https://www.pokewiki.de/Magnetilo -> https://www.pokewiki.de/Magneton